import "./globals.css";
import { DefaultLayout } from "@/components/templates/DefaultLayout";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Manage",
  description: "Generated by Manage",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body className={inter.className + " h-screen w-screen"}>
        <DefaultLayout>{children}</DefaultLayout>
      </body>
    </html>
  );
}
