version: "3"

services:
  # MySQL
  db:
    image: mysql:8
    container_name: mysql_host
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: manage
      MYSQL_USER: manage
      MYSQL_PASSWORD: password
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./tmp/db/data:/var/lib/mysql
      - ./tmp/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./tmp/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 5304:3306
